version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my_sql_server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SQLSUTTER@123"
      MSSQL_PID: "developer"
    ports:
      - "1433:1433"
